version: '3.7'
services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  grafana:
    image: grafana/grafana:8.0.0
    ports:
      - "3000:3000"
