version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"   # Host'ta 5001, container'da 5001
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
